_target_: src.datamodules.combine_datamodule.CombineDataModule

counterfactual_args:
  config: ${model.model_args}
  data_dir: ${data_dir} # data_dir is specified in config.yaml
  counterfactual_filename: "counterfactual_gt.json"
  monet_feature_path: "mask_based_features"
  batch_size: 64
  num_workers: 4
  pin_memory: False

descriptive_args:
  config: ${model.model_args}
  data_dir: ${data_dir} # data_dir is specified in config.yaml
  answer_map_name: "answer_map_des.pickle"
  descriptive_filename: "descriptive_gt.json"
  monet_feature_path: "mask_based_features"
  batch_size: 8
  num_workers: 4
  pin_memory: False